version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: porter-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"  # Using port 27018 to avoid conflict with existing MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - porter-network

volumes:
  mongodb_data:

networks:
  porter-network:
    driver: bridge